### PR TITLE
Pass urls to checkout

### PR DESCRIPTION
**Pull request by joshuakoh1**

### CODE REVIEW

**Comment by oscarychen** [comment]
@joshuakoh1  Why are the checkout urls passed from frontend? When would you do this?

**Comment by joshuakoh1** [comment]
To the checkout serializer together with price_id

**Comment by oscarychen** [comment]
When would you need web frontend to decide what the url to redirect to? This sounds like you may be potentially opening up opportunity to CSRF attack.

**Comment by joshuakoh1** [comment]
I have more than one frontend

**Comment by oscarychen** [comment]
I'd suggest implement a whitelist

**Pull request closed without merging**
